const content = "Kami hadir sebagai informasi jurusan kepada anak sekolah yang ingin melanjutkan ke pengguruan tinggi";

const dataJurusans = [
    {
      nama: 'Sistem Informasi',
      title: 'Memfokuskan pada pengembangan sistem informasi dan analisis bisnis. Mahasiswa dapat menjadi analis bisnis atau pengembang perangkat lunak setelah lulus.',
      deskripsi: 'Sistem Informasi adalah suatu rangkaian elemen-elemen yang saling terkait dan bekerja sama untuk mengumpulkan, menyimpan, memproses, mengelola, dan menyajikan informasi guna mendukung pengambilan keputusan di suatu organisasi atau entitas. Sistem ini dirancang untuk mengatasi kebutuhan informasi yang spesifik dengan mengintegrasikan teknologi, manusia, dan prosedur bisnis. Komponen-komponen utama dalam sistem informasi meliputi perangkat keras (hardware), perangkat lunak (software), basis data, jaringan komunikasi, serta pengguna atau manusia yang berinteraksi dengan sistem tersebut. Sistem informasi dapat mencakup berbagai jenis, seperti Sistem Informasi Manajemen (SIM) yang fokus pada dukungan keputusan manajerial, Sistem Informasi Akuntansi (SIA) yang berfokus pada proses akuntansi, dan Sistem Informasi Geografis (SIG) yang menyajikan informasi spasial. Keberhasilan suatu sistem informasi tergantung pada perancangan yang baik, pemeliharaan yang teratur, dan adaptasi terhadap perubahan lingkungan bisnis atau organisasi.',
      gambar: require('./assets/si.png'),
    },
    {
      nama: 'Rekayasa Perangkat Lunak',
      title: 'Menekankan pengembangan perangkat lunak, melibatkan desain, pengujian, dan manajemen proyek. Mahasiswa siap menjadi pengembang perangkat lunak atau engineer TI.',
      deskripsi:'Rekayasa Perangkat Lunak (RPL) adalah disiplin ilmu yang berkaitan dengan proses pengembangan perangkat lunak secara sistematis, efisien, dan terukur. RPL melibatkan serangkaian aktivitas, mulai dari perencanaan hingga pemeliharaan, dengan tujuan menghasilkan produk perangkat lunak yang berkualitas tinggi. Proses pengembangan RPL mencakup analisis kebutuhan, perancangan sistem, implementasi, pengujian, dan pemeliharaan. Para profesional RPL berusaha untuk mencapai tujuan pengembangan perangkat lunak dengan mematuhi standar dan praktik terbaik industri. Model pengembangan perangkat lunak, seperti model air terjun, model prototipe, dan metode Agile, dapat digunakan sesuai dengan kebutuhan proyek. Selain itu, RPL juga memperhatikan manajemen proyek, pengelolaan risiko, dan aspek kualitas produk. Dengan pendekatan yang matang dalam RPL, diharapkan dapat dihasilkan perangkat lunak yang memenuhi harapan pengguna, dapat diandalkan, mudah dipelihara, dan dapat beradaptasi dengan perubahan kebutuhan yang mungkin terjadi.',
      gambar: require('./assets/rpl.png'),
    },
    {
      nama: 'Teknik Informatika',
      title: 'Fokus pada pengembangan perangkat lunak, jaringan, dan sistem informasi. Mahasiswa mempelajari teknologi untuk karir sebagai pengembang perangkat lunak atau ahli jaringan',
      deskripsi:'Teknik Informatika adalah cabang ilmu komputer yang fokus pada pengembangan dan penerapan teknologi informasi, terutama dalam konteks perangkat lunak dan sistem komputer. Disiplin ini mencakup berbagai aspek, mulai dari perancangan algoritma, pemrograman, analisis dan perancangan sistem informasi, hingga manajemen proyek pengembangan perangkat lunak. Mahasiswa Teknik Informatika memperoleh pemahaman mendalam tentang konsep-konsep komputasi, struktur data, basis data, jaringan komputer, keamanan informasi, dan kecerdasan buatan. Selain itu, mereka juga dilatih untuk menerapkan metode pengembangan perangkat lunak yang efektif dan efisien. Dengan perkembangan teknologi yang cepat, para profesional Teknik Informatika berperan penting dalam inovasi dan transformasi digital di berbagai sektor, seperti bisnis, kesehatan, pendidikan, dan industri. Pemahaman yang kokoh dalam Teknik Informatika memungkinkan mereka untuk merancang solusi teknologi informasi yang relevan, terukur, dan dapat memberikan dampak positif dalam lingkungan masyarakat dan dunia usaha.',
      gambar: require('./assets/teknik.png'),
    },
    {
      nama: 'Teknologi Informasi',
      title: 'Fokus pada penerapan teknologi dalam bisnis, melibatkan manajemen sistem dan keamanan informasi untuk mempersiapkan mahasiswa sebagai profesional TI.',
      deskripsi:'Teknologi Informasi (TI) mencakup segala aspek yang terkait dengan penggunaan komputer, perangkat keras, perangkat lunak, dan jaringan komunikasi untuk mengumpulkan, menyimpan, mengolah, dan menyebarkan informasi. Dalam lingkup lebih luas, TI tidak hanya mencakup teknologi komputer, tetapi juga sistem komunikasi, infrastruktur jaringan, serta aplikasi dan layanan yang digunakan untuk mengelola dan mentransmisikan data. Teknologi Informasi digunakan dalam berbagai sektor, seperti bisnis, pendidikan, kesehatan, pemerintahan, dan industri. Ini mencakup pembangunan perangkat lunak, manajemen basis data, keamanan informasi, analisis data, dan layanan komunikasi. Pengembangan TI juga mencakup tren seperti komputasi awan, kecerdasan buatan, dan internet of things (IoT). Dengan peranannya yang semakin mendalam dan meresap dalam kehidupan sehari-hari, Teknologi Informasi terus menjadi kekuatan penggerak inovasi, efisiensi, dan transformasi dalam masyarakat modern. Perkembangan TI memberikan dampak signifikan pada cara orang berinteraksi, bekerja, dan mengakses informasi di era digital ini.',
      gambar: require('./assets/teknologi.png'),
    },
    {
      nama: 'Sains Data',
      title: 'Memanfaatkan analisis data dan pembelajaran mesin untuk pengambilan keputusan. Mahasiswa dilatih dalam statistik dan pemrograman untuk menjadi ahli analisis data.',
      deskripsi:'Sains Data merupakan disiplin ilmu interdisipliner yang menggabungkan konsep statistika, matematika, dan pemrograman komputer untuk menganalisis, menginterpretasi, dan mengambil keputusan berdasarkan data. Fokus utama sains data adalah pada penggalian wawasan dari set data yang besar dan kompleks, yang dikenal sebagai Big Data. Para profesional sains data menggunakan teknik-teknik seperti analisis statistik, machine learning, dan data mining untuk mengidentifikasi pola, tren, dan hubungan dalam data. Selain itu, mereka juga bertanggung jawab untuk merancang dan mengimplementasikan model prediktif serta solusi yang dapat memberikan nilai tambah dalam pengambilan keputusan. Sains Data memiliki peran krusial dalam berbagai sektor, termasuk bisnis, kesehatan, keuangan, dan penelitian ilmiah. Dengan kemampuannya untuk meramalkan, mengoptimalkan, dan mengelola data dengan cermat, sains data membantu organisasi dan individu untuk membuat keputusan yang lebih informasional dan strategis dalam menghadapi tantangan di era digital ini.',
      gambar: require('./assets/sd.png')
    },
    {
      nama: 'Bisnis Digital',
      title: 'Menerapkan teknologi digital untuk operasi dan pemasaran bisnis. Mahasiswa mempelajari strategi online dan analisis data.',
      deskripsi:'Bisnis Digital mencerminkan transformasi radikal dalam cara organisasi beroperasi dan berinteraksi dengan pelanggan, didorong oleh pemanfaatan teknologi digital. Dalam konteks ini, perusahaan menggunakan teknologi informasi dan komunikasi untuk meningkatkan proses bisnis, memperluas jangkauan pasar, dan meningkatkan efisiensi operasional. Bisnis Digital melibatkan pemanfaatan platform online, e-commerce, analisis data, kecerdasan buatan, dan teknologi lainnya untuk menciptakan pengalaman pelanggan yang lebih personal, mempercepat inovasi produk, dan mengoptimalkan rantai pasokan. Model bisnis yang berpusat pada digital memungkinkan perusahaan untuk beradaptasi dengan cepat terhadap perubahan pasar dan mendapatkan wawasan yang lebih mendalam melalui analisis data. Selain itu, penerapan strategi pemasaran digital, seperti media sosial dan kampanye online, memainkan peran penting dalam membangun merek dan menjangkau konsumen secara global. Bisnis Digital bukan hanya sekadar mengadopsi teknologi, melainkan juga mengubah paradigma dalam strategi bisnis, menciptakan peluang baru, dan memberikan nilai tambah melalui inovasi teknologi dalam ekosistem bisnis dunia yang terus berkembang.',
      gambar: require('./assets/bd.png'),
    },
    {
      nama: 'Teknik Telekomunikasi',
      title: 'Fokus pada desain dan manajemen sistem komunikasi, termasuk jaringan dan transmisi data. Mahasiswa mempersiapkan diri untuk karir di bidang teknologi telekomunikasi.',
      deskripsi:'Teknik Telekomunikasi adalah cabang ilmu dan teknik yang berkaitan dengan desain, instalasi, operasi, dan pemeliharaan sistem komunikasi yang melibatkan pengiriman informasi suara, data, dan video melalui saluran transmisi jarak jauh. Disiplin ini mencakup berbagai teknologi, termasuk telepon, televisi, radio, dan jaringan komunikasi data. Para profesional di bidang Teknik Telekomunikasi memiliki pemahaman mendalam tentang prinsip-prinsip sinyal, modulasi, multiplexing, dan teknologi transmisi data. Mereka merancang, mengimplementasikan, dan mengelola infrastruktur telekomunikasi, termasuk perangkat keras seperti antena, pemancar, dan perangkat lunak yang mendukung fungsi jaringan. Dengan perkembangan teknologi yang pesat, Teknik Telekomunikasi juga terus mengembangkan solusi inovatif seperti jaringan 5G, Internet of Things (IoT), dan komunikasi satelit. Dalam era globalisasi ini, Teknik Telekomunikasi memiliki peran krusial dalam memfasilitasi konektivitas dan pertukaran informasi antar individu, perusahaan, dan negara, menjadikannya elemen kunci dalam mendorong perkembangan teknologi dan komunikasi di seluruh dunia.',
      gambar: require('./assets/tt.png'),
    },
    {
      nama: 'Teknik Komputer',
      title: 'Fokus pada perancangan dan pemeliharaan perangkat keras komputer. Mahasiswa mempelajari arsitektur dan pemrograman untuk karir di pengembangan perangkat keras atau teknisi komputer.',
      deskripsi:'Teknik Komputer adalah disiplin ilmu yang terfokus pada perancangan, pengembangan, implementasi, dan pemeliharaan sistem komputer serta perangkat lunaknya. Para profesional di bidang ini, dikenal sebagai insinyur komputer, memiliki pemahaman mendalam tentang arsitektur komputer, perangkat keras, perangkat lunak, dan jaringan komputer. Mereka terlibat dalam merancang dan membangun komponen-komponen perangkat keras, seperti mikroprosesor, memori, dan perangkat penyimpanan, serta mengembangkan perangkat lunak untuk berbagai aplikasi, mulai dari sistem operasi hingga aplikasi bisnis dan game. Teknik Komputer juga mencakup disiplin seperti keamanan komputer, kecerdasan buatan, dan pemrosesan citra. Dalam konteks era digital ini, Teknik Komputer memiliki peran penting dalam memfasilitasi transformasi digital di berbagai sektor, seperti industri, kesehatan, pendidikan, dan hiburan. Keahlian insinyur komputer sangat diperlukan dalam menciptakan solusi teknologi yang inovatif dan dapat meningkatkan efisiensi, produktivitas, serta pengalaman pengguna dalam penggunaan teknologi komputer.',
      gambar: require('./assets/tk.png'),
    },
    {
      nama: 'Sistem Komputer',
      title : 'Desain, pengembangan, dan pemeliharaan perangkat keras dan perangkat lunak. Mahasiswa siap karir di pengembangan teknologi atau administrasi sistem.',
      deskripsi : 'Sistem Komputer adalah entitas yang terdiri dari perangkat keras dan perangkat lunak yang bekerja bersama-sama untuk memproses informasi dan menjalankan fungsi-fungsi komputasi. Perangkat keras mencakup komponen fisik seperti prosesor, memori, penyimpanan data, dan perangkat input/output, sementara perangkat lunak melibatkan sistem operasi, aplikasi, dan program-program yang mengatur operasi sistem. Sistem Komputer dirancang untuk melakukan tugas-tugas komputasi seperti pengolahan data, penghitungan, dan eksekusi instruksi-program. Arsitektur sistem komputer umumnya terdiri dari unit pemrosesan utama, unit penyimpanan, dan unit input/output, yang saling berinteraksi untuk menciptakan lingkungan komputasi yang berfungsi. Sistem Komputer dapat berkisar dari perangkat pribadi hingga server pusat data yang kompleks. Keberhasilan suatu sistem komputer bergantung pada integrasi yang efisien antara perangkat keras dan perangkat lunak, serta pemeliharaan yang teratur untuk memastikan kinerja optimal dan keamanan sistem. Dengan peran sentralnya dalam berbagai bidang, sistem komputer menjadi tulang punggung teknologi modern dan memainkan peran vital dalam kemajuan masyarakat di era digital ini.',
      gambar: require('./assets/sk.png'),
    },
    {
      nama: 'Teknik Elektro',
      title: 'Fokus pada pengembangan, desain, dan pemeliharaan perangkat elektronik. Mahasiswa siap untuk karir di desain, instalasi, atau pemrograman perangkat elektronik.',
      deskripsi:'Teknik Elektro adalah cabang ilmu dan rekayasa yang memfokuskan diri pada studi, perancangan, dan pengembangan perangkat dan sistem yang menggunakan listrik, elektronika, dan elektromagnetika. Para profesional di bidang Teknik Elektro, atau insinyur elektro, memiliki pemahaman mendalam tentang prinsip-prinsip listrik, sirkuit, dan perangkat elektronik. Mereka terlibat dalam merancang, mengembangkan, dan memelihara berbagai sistem dan perangkat, seperti perangkat telekomunikasi, kendaraan listrik, perangkat medis, dan peralatan otomatisasi industri. Bidang spesialisasi Teknik Elektro meliputi elektronika daya, kendali dan otomasi, komunikasi, sinyal dan sistem, serta mikroelektronika. Seiring dengan kemajuan teknologi, Teknik Elektro juga memainkan peran penting dalam pengembangan teknologi baru seperti Internet of Things (IoT), kecerdasan buatan, dan energi terbarukan. Dalam dunia modern yang terus berubah, Teknik Elektro menjadi pendorong utama inovasi teknologi yang memengaruhi hampir semua aspek kehidupan sehari-hari dan berperan besar dalam membentuk masa depan teknologi global.',
      gambar: require('./assets/te.png'),
    },
  ];

export default dataJurusans;